### ISSUE TITLE
error when install using pip install Opy with python3.5

### ISSUE THREAD

**Issue by NewUserHa** [QQuick/Opy#25]
```
C:\Windows\system32>pip install Opy
Collecting Opy
  Using cached Opy-1.1.27.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-864qjt_y\Opy\setup.py", line 18, in <module>
        read ('README.rst') + '\n\n' +
      File "C:\Users\user\AppData\Local\Temp\pip-build-864qjt_y\Opy\setup.py", line 11, in read
        return aFile.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 3715: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-864qjt_y\Opy\
```

**Comment by JdeH** [comment]
A patch was uploaded.
Let me know if it works for you.

Kind regards
Jacques

**Comment by NewUserHa** [comment]
solved

**Comment by JdeH** [comment]
Thx
